### ISSUE TITLE
ChatGLM Exception during processing

### ISSUE THREAD

**Issue by LankyPoet** [kijai/ComfyUI-KwaiKolorsWrapper#21]
Hi, thanks for making this.
![image](https://github.com/kijai/ComfyUI-KwaiKolorsWrapper/assets/146845805/b930a2b4-b47e-4e80-95bd-9297f93c1b5e)
Whenever I try to load from the ChatGLM node, I get the below error. I followed your readme instructions and have in my models\LLM\checkpoints directory:
![image](https://github.com/kijai/ComfyUI-KwaiKolorsWrapper/assets/146845805/6f6d93e0-0ce9-44b9-a480-46f0f0420e1f)

I have tried all 3 quants. Can you help me understand best next steps?

`Load TEXT_ENCODER...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████| 7/7 [00:07<00:00,  1.06s/it]
!!! Exception during processing!!! stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "D:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\nodes.py", line 190, in loadmodel
    tokenizer = ChatGLMTokenizer.from_pretrained(text_encoder_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\transformers\tokenization_utils_base.py", line 2163, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\transformers\tokenization_utils_base.py", line 2397, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\tokenization_chatglm.py", line 101, in __init__
    self.tokenizer = SPTokenizer(vocab_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\tokenization_chatglm.py", line 14, in __init__
    assert os.path.isfile(model_path), model_path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 30, in isfile
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType`

**Comment by LankyPoet** [comment]
I completely cleared out the downloaded files, deleted the node pack directory, then restarted from scratch. Everything works now.

**Comment by yatoubusha** [comment]
what's difference between your twice operations? i got the same problem.
