### ISSUE TITLE
Library cublasLt is not initialized

### ISSUE THREAD

**Issue by c4dee** [kijai/ComfyUI-KwaiKolorsWrapper#22]
Anyone seen this before and can help please? 

```
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [00:24<00:00,  3.50s/it]
Symbol cudaLaunchKernel not found in C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common\cudart64_65.dll
!!! Exception during processing!!! Library cublasLt is not initialized
Traceback (most recent call last):
  File "F:\Programme\ComfyUI Portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\Programme\ComfyUI Portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\Programme\ComfyUI Portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\Programme\ComfyUI Portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\nodes.py", line 188, in loadmodel
    text_encoder.quantize(4)
  File "F:\Programme\ComfyUI Portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\modeling_chatglm.py", line 852, in quantize
    quantize(self.encoder, weight_bit_width)
  File "F:\Programme\ComfyUI Portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\quantization.py", line 155, in quantize
    layer.self_attention.query_key_value = QuantizedLinear(
  File "F:\Programme\ComfyUI Portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\quantization.py", line 139, in __init__
    self.weight = compress_int4_weight(self.weight)
  File "F:\Programme\ComfyUI Portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\models\quantization.py", line 78, in compress_int4_weight
    kernels.int4WeightCompression(
  File "F:\Programme\ComfyUI Portable\python_embeded\lib\site-packages\cpm_kernels\kernels\base.py", line 48, in __call__
    func = self._prepare_func()
  File "F:\Programme\ComfyUI Portable\python_embeded\lib\site-packages\cpm_kernels\kernels\base.py", line 40, in _prepare_func
    self._module.get_module(), self._func_name
  File "F:\Programme\ComfyUI Portable\python_embeded\lib\site-packages\cpm_kernels\kernels\base.py", line 23, in get_module
    Device(curr_device).use()   # force initialize context
  File "F:\Programme\ComfyUI Portable\python_embeded\lib\site-packages\cpm_kernels\device\__init__.py", line 152, in use
    self._device.use()
  File "F:\Programme\ComfyUI Portable\python_embeded\lib\site-packages\cpm_kernels\device\__init__.py", line 120, in use
    self.cublasLtHandle = cublaslt.cublasLtCreate()
  File "F:\Programme\ComfyUI Portable\python_embeded\lib\site-packages\cpm_kernels\library\base.py", line 72, in wrapper
    raise RuntimeError("Library %s is not initialized" % self.__name)
RuntimeError: Library cublasLt is not initialized
```

**Comment by c4dee** [comment]
For some reason it works now. I restarted ComfyUI several times.
