### ISSUE TITLE
RuntimeError: Failed to import diffusers.loaders.single_file

### ISSUE THREAD

**Issue by Duemellon** [kijai/ComfyUI-KwaiKolorsWrapper#31]
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\nodes.py", line 16, in <module>
    from .kolors.pipelines.pipeline_stable_diffusion_xl_chatglm_256 import StableDiffusionXLPipeline
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper\kolors\pipelines\pipeline_stable_diffusion_xl_chatglm_256.py", line 21, in <module>
    from diffusers.loaders import FromSingleFileMixin, LoraLoaderMixin
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\Python\Python310\lib\site-packages\diffusers\utils\import_utils.py", line 798, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\Python\Python310\lib\site-packages\diffusers\utils\import_utils.py", line 810, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import diffusers.loaders.single_file because of the following error (look up to see its traceback):
Failed to import transformers.models.auto.image_processing_auto because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper module for custom nodes: Failed to import diffusers.loaders.single_file because of the following error (look up to see its traceback):
Failed to import transformers.models.auto.image_processing_auto because of the following error (look up to see its traceback):
Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
### ComfyUI Revision: 2383 [11b74147] | Released on '2024-07-19'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
#install llama-cpp-python error

**Comment by Duemellon** [comment]
I'm using the default workflow.

Ran ComfyUI and the nodes came up instead of being red. However, when I told it to run I still got:

![image](https://github.com/user-attachments/assets/0e77cd1a-aa0e-403e-899f-de5908028b27)

I deleted all the GetVAE/connector wireless nodes & it progressed to the Sampler then bombed with

![image](https://github.com/user-attachments/assets/debd11c3-16ed-495b-bb4c-b05f364222fa)

Guess I need to figure out where/how to get the Euler recognized/installed

**Comment by kijai** [comment]
I think your diffusers install is just outdated.
